[package]
name = "file_encryption"
version = "0.1.0"
authors = ["张建新 <zhangjianxin@bigsfintech.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
